model_path: /lustre/ssd/ws/dchristi-3dseg/checkpoints/model_96x96x96_00/best_checkpoint.pytorch
device: cuda:0
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 3
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
  output_type: 'classes' # 'probability'
loaders:
  dataset: StandardHDF5Dataset
  # save predictions to output_dir
  output_dir: /lustre/ssd/ws/dchristi-3dseg/predict//model_96x96x96_00/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 24
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [32, 32, 32]
  # how many subprocesses to use for data loading
  num_workers: 24
  # test loaders configuration
  test:
    file_paths:
      - /lustre/ssd/ws/dchristi-3dseg/data/160_10-layer/volumes/00/rand_subvolume/160_10-layer_00_0.h5
      - /lustre/ssd/ws/dchristi-3dseg/data/160_10-layer/volumes/00/rand_subvolume/160_10-layer_00_1.h5
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better) origninal [80,170,170]
      patch_shape: [96, 96, 96]
      # train stride between patches
      stride_shape: [16, 16, 16]
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
