
device: cuda:0
model_path: /data/horse/ws/dchristi-3dseg/checkpoints/NEAPEL/NEAPEL_run_004/best_checkpoint.pytorch
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 4
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'StandardPredictor'
  output_type: 'probabilities'
loaders:
  # save predictions to output_dir
  output_dir: /data/horse/ws/dchristi-3dseg/predict/NEAPEL/NEAPEL_run_004/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 8
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [16, 32, 32]
  # how many subprocesses to use for data loading
  num_workers: 24
  # test loaders configuration
  test:
    file_paths:
      - /data/horse/ws/dchristi-3dseg/data/NEAPEL/Thinlayer 1-3_tomo-HR_recon_aligned-gzip_subvolume_1.h5
    slice_builder:
      name: SliceBuilder
      patch_shape: [40, 256, 256]
      stride_shape: [24, 240, 240]
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
